# Generated by Django 4.1.2 on 2022-11-17 12:26

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BLOG_COMMENT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default='', help_text='No need to edit this field.', max_length=100)),
                ('quote_header', models.CharField(blank=True, default='', max_length=1000)),
                ('quote_writer_name', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=500)),
                ('website', models.CharField(blank=True, default='', max_length=500)),
                ('message', models.TextField(blank=True, default='')),
                ('permission', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BLOG_POST',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default=uuid.uuid4, help_text='No need to edit this field.', max_length=100)),
                ('comment', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('text', 'text'), ('image', 'image'), ('video', 'video'), ('quote', 'quote')], default='image', max_length=50)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, default='', upload_to='images/blog')),
                ('video', models.TextField(blank=True, default='', help_text='Paste a video video iframe link.')),
                ('quote_header', models.CharField(blank=True, default='', max_length=1000)),
                ('quote_writer_name', models.CharField(blank=True, default='', max_length=100)),
                ('topic', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
