# Generated by Django 4.1.2 on 2022-11-17 12:26

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CONTACT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='JOB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default=uuid.uuid4, help_text='No need to edit this field.', max_length=100)),
                ('picture', models.ImageField(blank=True, default='', upload_to='images/jobs')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(blank=True, choices=[('All', 'All'), ('Remote', 'Remote'), ('Foreign', 'Foreign'), ('Pakistan', 'Pakistan')], default='All', max_length=50)),
                ('timing', models.CharField(blank=True, choices=[('Temporary', 'Temporary'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Freelance', 'Freelance'), ('Goverment', 'Goverment'), ('Private', 'Private')], default='Private', max_length=50)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('out_location', models.CharField(blank=True, default='', max_length=100)),
                ('out_category', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('website_link', models.CharField(blank=True, default='', max_length=100)),
                ('map', models.TextField(blank=True, default='', help_text='Paste link from the google map.')),
                ('applications', models.CharField(blank=True, default='', max_length=100)),
                ('visitors', models.CharField(blank=True, default='0', help_text='Original value will be add in your value.', max_length=100)),
                ('remaining_days', models.CharField(blank=True, default='0', help_text='Original value will be add in your value.', max_length=100)),
                ('salary', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Male - Female', 'Male - Female')], default='Male - Female', max_length=50)),
                ('career_level', models.CharField(blank=True, default='', max_length=100)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('experience', models.CharField(blank=True, default='', max_length=100)),
                ('qualifications', models.CharField(blank=True, default='', max_length=100)),
                ('jobs_descriptions', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('require_knowledge_skills_abilities', models.TextField(blank=True, default='', help_text='Break point with ($$$)')),
                ('education_experience', models.TextField(blank=True, default='', help_text='Break point with ($$$)')),
            ],
        ),
        migrations.CreateModel(
            name='NEWSLETTER',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
